name: 'hello-world'
description: 'Greed someone and record the time'

inputs:
  who-to-greed:
    description: who to greed
    required: true
    default: 'World'
    
outputs:
  time:
    description: 'The timw we greed you'
    
runs:
   using: 'node16'
   main: 'index.js'
   
const core = require('@actions/core');
const github = require('@actions/github');

try {
  // Fetch the value of the input 'who-to-greet' specified in action.yml
  const nameToGreet = core.getInput('who-to-greet');
  console.log(`Hello ${nameToGreet}!`);
  
  // Record the time of greeting as an output
  const time = (new Date()).toTimeString();
  core.setOutput("time", time);

} catch (error) {
  // Handle errors and indicate failure
  core.setFailed(error.message);
}
