name : hello-world
on: push
jobs:
  built:
    runs-on: ubuntu-latest
    steps:
     - name: checkout repo
       uses: actions/checkout@v4.1.2
     - name: use node.js
       uses: action/setup-node@v4.1.2
       with:
         node-version: '18.x'
     - run: npm install
     - run: npm run build
